DROP TABLE product_identifiers;
DROP TABLE descriptions;
DROP TABLE products;
DROP TABLE clients;



CREATE TABLE clients (
    client_id VARCHAR2(255) NOT NULL,
    name VARCHAR2(255),
    email VARCHAR2(255),
    PRIMARY KEY (client_id)
);


CREATE TABLE products (
    id VARCHAR2(255) NOT NULL,
    client_id VARCHAR2(255) NOT NULL,
    product_name VARCHAR2(255),
    product_type VARCHAR2(50),
    status VARCHAR2(50),
    start_date VARCHAR2(50),
    subscription_type VARCHAR2(50),
    PRIMARY KEY (id),
    FOREIGN KEY (client_id) REFERENCES clients(client_id) ON DELETE CASCADE
);



CREATE TABLE descriptions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR2(1000),
    url VARCHAR2(255),
    category VARCHAR2(100),
    product_id VARCHAR2(255),
    PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);


CREATE TABLE product_identifiers (
    product_id VARCHAR2(255) NOT NULL,
    identifier VARCHAR2(255),
    PRIMARY KEY (product_id, identifier),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);






-- Inserção de um cliente
INSERT INTO clients (client_id, name, email) VALUES ('c100', 'Jane Doe', 'jane.doe@example.com');

-- Inserção de produtos associados ao cliente
INSERT INTO products (id, client_id, product_name, product_type, status, start_date, subscription_type)
VALUES ('p100', 'c100', 'Smartphone', 'Electronics', 'Active', '2022-01-01', 'Prepaid');

-- Consulta de produtos de um cliente específico
SELECT * FROM products WHERE client_id = 'c100';
